version: "3"
########
volumes:
  clg-db:
    name: clg-db
#########
networks:
  clg-network:
    name: clg-network
##########
services:
  clg-db:
    container_name: clg-db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-clg_api}
      PGDATA: /data/postgres
    volumes:
       - clg-db:/data/postgres
    networks:
      - clg-network
    restart: unless-stopped
##########
  clg-api:
    image: clg-api:${VERSION:-0.1}
    build:
      context: ./api
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    volumes:
      - ./api:/usr/src/app/api
    depends_on:
      - clg-db
    expose:
      - 8081
    restart: unless-stopped
    environment:
      PORT: ${API_PORT:-8081}
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASSWORD:-postgres}
      DB_HOST: clg-db
      DB_NAME: ${DB_NAME:-clg_api}
      DB_PORT: ${DB_PORT:-5432}
    networks:
      - clg-network
###########
  clg-web:
    image: clg-web:${VERSION:-0.1}
    build:
      context: ./web
      target: ${NODE_ENV:-development}
    depends_on:
      - clg-api
    volumes:
      - ./web:/usr/src/app/web
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${WEB_PORT:-8080}
      API_HOST: ${API_HOST:-http://clg-api:8081}
    networks:
      - clg-network